[features]
seeds = false
skip-lint = false
[programs.localnet]
mysolanaapp = "72fJ18jk36MnJkwi1e1YkeUC7giAUU7UJ2DbzkXHMJBt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ducnguyen/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
